//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package teamcloud

// ClientCancelComponentTaskResponse contains the response from method Client.CancelComponentTask.
type ClientCancelComponentTaskResponse struct {
	// // Possible types are ComponentTaskDataResult, StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateComponentResponse contains the response from method Client.CreateComponent.
type ClientCreateComponentResponse struct {
	// // Possible types are ComponentDataResult, StatusResult, ErrorResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateComponentTaskResponse contains the response from method Client.CreateComponentTask.
type ClientCreateComponentTaskResponse struct {
	// // Possible types are ComponentTaskDataResult, StatusResult, ErrorResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateDeploymentScopeResponse contains the response from method Client.CreateDeploymentScope.
type ClientCreateDeploymentScopeResponse struct {
	// // Possible types are DeploymentScopeDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateOrganizationResponse contains the response from method Client.CreateOrganization.
type ClientCreateOrganizationResponse struct {
	// // Possible types are OrganizationDataResult, ErrorResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateOrganizationUserResponse contains the response from method Client.CreateOrganizationUser.
type ClientCreateOrganizationUserResponse struct {
	// // Possible types are UserDataResult, ErrorResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateProjectIdentityResponse contains the response from method Client.CreateProjectIdentity.
type ClientCreateProjectIdentityResponse struct {
	// // Possible types are ProjectIdentityDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateProjectResponse contains the response from method Client.CreateProject.
type ClientCreateProjectResponse struct {
	// // Possible types are ProjectDataResult, StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateProjectTagResponse contains the response from method Client.CreateProjectTag.
type ClientCreateProjectTagResponse struct {
	// // Possible types are StatusResult, ErrorResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateProjectTemplateResponse contains the response from method Client.CreateProjectTemplate.
type ClientCreateProjectTemplateResponse struct {
	// // Possible types are ProjectTemplateDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateProjectUserResponse contains the response from method Client.CreateProjectUser.
type ClientCreateProjectUserResponse struct {
	// // Possible types are UserDataResult, StatusResult, ErrorResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientCreateScheduleResponse contains the response from method Client.CreateSchedule.
type ClientCreateScheduleResponse struct {
	// // Possible types are ScheduleDataResult, ErrorResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientDeleteComponentResponse contains the response from method Client.DeleteComponent.
type ClientDeleteComponentResponse struct {
	// // Possible types are StatusResult, ComponentDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientDeleteDeploymentScopeResponse contains the response from method Client.DeleteDeploymentScope.
type ClientDeleteDeploymentScopeResponse struct {
	// // Possible types are DeploymentScopeDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientDeleteOrganizationResponse contains the response from method Client.DeleteOrganization.
type ClientDeleteOrganizationResponse struct {
	// // Possible types are StatusResult, ErrorResult
	Value interface{}
}

// ClientDeleteOrganizationUserResponse contains the response from method Client.DeleteOrganizationUser.
type ClientDeleteOrganizationUserResponse struct {
	// // Possible types are StatusResult, UserDataResult, ErrorResult
	Value interface{}
}

// ClientDeleteProjectIdentityResponse contains the response from method Client.DeleteProjectIdentity.
type ClientDeleteProjectIdentityResponse struct {
	// // Possible types are ProjectIdentityDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientDeleteProjectResponse contains the response from method Client.DeleteProject.
type ClientDeleteProjectResponse struct {
	// // Possible types are StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientDeleteProjectTagResponse contains the response from method Client.DeleteProjectTag.
type ClientDeleteProjectTagResponse struct {
	// // Possible types are StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientDeleteProjectTemplateResponse contains the response from method Client.DeleteProjectTemplate.
type ClientDeleteProjectTemplateResponse struct {
	// // Possible types are ProjectTemplateDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientDeleteProjectUserResponse contains the response from method Client.DeleteProjectUser.
type ClientDeleteProjectUserResponse struct {
	// // Possible types are StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetAdaptersResponse contains the response from method Client.GetAdapters.
type ClientGetAdaptersResponse struct {
	// // Possible types are AdapterInformationListDataResult, ErrorResult
	Value interface{}
}

// ClientGetAuditCommandsResponse contains the response from method Client.GetAuditCommands.
type ClientGetAuditCommandsResponse struct {
	// // Possible types are StringListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetAuditEntriesResponse contains the response from method Client.GetAuditEntries.
type ClientGetAuditEntriesResponse struct {
	// // Possible types are CommandAuditEntityListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetAuditEntryResponse contains the response from method Client.GetAuditEntry.
type ClientGetAuditEntryResponse struct {
	// // Possible types are CommandAuditEntityDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetComponentResponse contains the response from method Client.GetComponent.
type ClientGetComponentResponse struct {
	// // Possible types are ComponentDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetComponentTaskResponse contains the response from method Client.GetComponentTask.
type ClientGetComponentTaskResponse struct {
	// // Possible types are ComponentTaskDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetComponentTasksResponse contains the response from method Client.GetComponentTasks.
type ClientGetComponentTasksResponse struct {
	// // Possible types are ComponentTaskListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetComponentTemplateResponse contains the response from method Client.GetComponentTemplate.
type ClientGetComponentTemplateResponse struct {
	// // Possible types are ComponentTemplateDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetComponentTemplatesResponse contains the response from method Client.GetComponentTemplates.
type ClientGetComponentTemplatesResponse struct {
	// // Possible types are ComponentTemplateListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetComponentsResponse contains the response from method Client.GetComponents.
type ClientGetComponentsResponse struct {
	// // Possible types are ComponentListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetDeploymentScopeResponse contains the response from method Client.GetDeploymentScope.
type ClientGetDeploymentScopeResponse struct {
	// // Possible types are DeploymentScopeDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetDeploymentScopesResponse contains the response from method Client.GetDeploymentScopes.
type ClientGetDeploymentScopesResponse struct {
	// // Possible types are DeploymentScopeListDataResult, ErrorResult
	Value interface{}
}

// ClientGetInfoResponse contains the response from method Client.GetInfo.
type ClientGetInfoResponse struct {
	InformationDataResult
}

// ClientGetOrganizationResponse contains the response from method Client.GetOrganization.
type ClientGetOrganizationResponse struct {
	// // Possible types are OrganizationDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetOrganizationUserMeResponse contains the response from method Client.GetOrganizationUserMe.
type ClientGetOrganizationUserMeResponse struct {
	// // Possible types are UserDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetOrganizationUserResponse contains the response from method Client.GetOrganizationUser.
type ClientGetOrganizationUserResponse struct {
	// // Possible types are UserDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetOrganizationUsersResponse contains the response from method Client.GetOrganizationUsers.
type ClientGetOrganizationUsersResponse struct {
	// // Possible types are UserListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetOrganizationsResponse contains the response from method Client.GetOrganizations.
type ClientGetOrganizationsResponse struct {
	// // Possible types are OrganizationListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectIdentitiesResponse contains the response from method Client.GetProjectIdentities.
type ClientGetProjectIdentitiesResponse struct {
	// // Possible types are ProjectIdentityListDataResult, ErrorResult
	Value interface{}
}

// ClientGetProjectIdentityResponse contains the response from method Client.GetProjectIdentity.
type ClientGetProjectIdentityResponse struct {
	// // Possible types are ProjectIdentityDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectResponse contains the response from method Client.GetProject.
type ClientGetProjectResponse struct {
	// // Possible types are ProjectDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectStatusResponse contains the response from method Client.GetProjectStatus.
type ClientGetProjectStatusResponse struct {
	// // Possible types are StatusResult, StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectTagByKeyResponse contains the response from method Client.GetProjectTagByKey.
type ClientGetProjectTagByKeyResponse struct {
	// // Possible types are StringDictionaryDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectTagsResponse contains the response from method Client.GetProjectTags.
type ClientGetProjectTagsResponse struct {
	// // Possible types are StringDictionaryDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectTemplateResponse contains the response from method Client.GetProjectTemplate.
type ClientGetProjectTemplateResponse struct {
	// // Possible types are ProjectTemplateDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectTemplatesResponse contains the response from method Client.GetProjectTemplates.
type ClientGetProjectTemplatesResponse struct {
	// // Possible types are ProjectTemplateListDataResult, ErrorResult
	Value interface{}
}

// ClientGetProjectUserMeResponse contains the response from method Client.GetProjectUserMe.
type ClientGetProjectUserMeResponse struct {
	// // Possible types are UserDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectUserResponse contains the response from method Client.GetProjectUser.
type ClientGetProjectUserResponse struct {
	// // Possible types are UserDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectUsersResponse contains the response from method Client.GetProjectUsers.
type ClientGetProjectUsersResponse struct {
	// // Possible types are UserListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetProjectsResponse contains the response from method Client.GetProjects.
type ClientGetProjectsResponse struct {
	// // Possible types are ProjectListDataResult, ErrorResult
	Value interface{}
}

// ClientGetScheduleResponse contains the response from method Client.GetSchedule.
type ClientGetScheduleResponse struct {
	// // Possible types are ScheduleDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetSchedulesResponse contains the response from method Client.GetSchedules.
type ClientGetSchedulesResponse struct {
	// // Possible types are ScheduleListDataResult, ErrorResult
	Value interface{}
}

// ClientGetStatusResponse contains the response from method Client.GetStatus.
type ClientGetStatusResponse struct {
	// // Possible types are StatusResult, StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetUserProjectsMeResponse contains the response from method Client.GetUserProjectsMe.
type ClientGetUserProjectsMeResponse struct {
	// // Possible types are ProjectListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientGetUserProjectsResponse contains the response from method Client.GetUserProjects.
type ClientGetUserProjectsResponse struct {
	// // Possible types are ProjectListDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientInitializeAuthorizationResponse contains the response from method Client.InitializeAuthorization.
type ClientInitializeAuthorizationResponse struct {
	// // Possible types are DeploymentScopeDataResult, ErrorResult
	Value interface{}
}

// ClientNegotiateSignalRResponse contains the response from method Client.NegotiateSignalR.
type ClientNegotiateSignalRResponse struct {
	// placeholder for future response values
}

// ClientReRunComponentTaskResponse contains the response from method Client.ReRunComponentTask.
type ClientReRunComponentTaskResponse struct {
	// // Possible types are ComponentTaskDataResult, StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientRunScheduleResponse contains the response from method Client.RunSchedule.
type ClientRunScheduleResponse struct {
	// // Possible types are ScheduleDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientUpdateDeploymentScopeResponse contains the response from method Client.UpdateDeploymentScope.
type ClientUpdateDeploymentScopeResponse struct {
	// // Possible types are DeploymentScopeDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientUpdateOrganizationUserMeResponse contains the response from method Client.UpdateOrganizationUserMe.
type ClientUpdateOrganizationUserMeResponse struct {
	// // Possible types are UserDataResult, StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientUpdateOrganizationUserResponse contains the response from method Client.UpdateOrganizationUser.
type ClientUpdateOrganizationUserResponse struct {
	// // Possible types are UserDataResult, StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientUpdateProjectIdentityResponse contains the response from method Client.UpdateProjectIdentity.
type ClientUpdateProjectIdentityResponse struct {
	// // Possible types are StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientUpdateProjectTagResponse contains the response from method Client.UpdateProjectTag.
type ClientUpdateProjectTagResponse struct {
	// // Possible types are StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientUpdateProjectTemplateResponse contains the response from method Client.UpdateProjectTemplate.
type ClientUpdateProjectTemplateResponse struct {
	// // Possible types are ProjectTemplateDataResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientUpdateProjectUserMeResponse contains the response from method Client.UpdateProjectUserMe.
type ClientUpdateProjectUserMeResponse struct {
	// // Possible types are UserDataResult, StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientUpdateProjectUserResponse contains the response from method Client.UpdateProjectUser.
type ClientUpdateProjectUserResponse struct {
	// // Possible types are UserDataResult, StatusResult, ErrorResult, ErrorResult
	Value interface{}
}

// ClientUpdateScheduleResponse contains the response from method Client.UpdateSchedule.
type ClientUpdateScheduleResponse struct {
	// // Possible types are ScheduleDataResult, ErrorResult, ErrorResult, ErrorResult
	Value interface{}
}

